name: laravel-postcode-nl

services:

  composer:
    build:
      context: .
      dockerfile: docker/composer.dockerfile
    user: "${DEV_UID}:${DEV_UID}"
    volumes:
      - .:/app
    working_dir: /app

  php-8.2:
    image: php:8.2-cli-alpine
    user: "${DEV_UID}:${DEV_UID}"
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: vendor/bin/phpunit

  php-8.3:
    image: php:8.3-cli-alpine
    user: "${DEV_UID}:${DEV_UID}"
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: vendor/bin/phpunit

  php-8.4:
    image: php:8.4-cli-alpine
    user: "${DEV_UID}:${DEV_UID}"
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: vendor/bin/phpunit

  php-8.5:
    image: php:8.5-cli-alpine
    env_file:
      - .env
    user: "${DEV_UID}:${DEV_UID}"
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: vendor/bin/phpunit
