name: Tests

on:
  push:
    branches:
      - '*.x'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        laravel: [^11.0, ^12.0, ^13.0]
        php: [8.2, 8.3, 8.4]
        exclude:
          - laravel: ^13.0
            php: 8.2

    name: Laravel ${{ matrix.laravel }} with PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl
          coverage: none

      - name: Require Laravel
        run: composer require "laravel/laravel:${{ matrix.laravel }}" --dev

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: vendor/bin/phpunit
